CREATE OR REPLACE TRIGGER U1.DAILY_UPDATE_EVENT_TRG BEFORE INSERT ON DAILY_UPDATE_EVENT
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID IS NULL THEN
      SELECT DAILY_UPDATE_EVENT_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/

