create or replace force view u1.m_contract_auto_mvd as
select "RFO_CONTRACT_ID","CONTRACT_NUMBER","CONTRACT_DATE","DATE_BEGIN","BUYER_IIN","SELLER_IIN","VIN","AUTO_PRICE","INITIAL_PAYMENT","TECH_PASSPORT_DATE","CR_PROGRAM_CODE","CR_PROGRAM_NAME","POS_CODE","EXPERT_LOGIN","EXPERT_NAME","DATE_COLAT","MVD_STATUS_DATE" from M_CONTRACT_AUTO_MVD_PRE p
where p.mvd_status_date is null;
grant select on U1.M_CONTRACT_AUTO_MVD to LOADDB;
grant select on U1.M_CONTRACT_AUTO_MVD to LOADER;


