CREATE OR REPLACE TRIGGER U1.MONTHLY_UPDATE_LOG_TRG
BEFORE INSERT ON MONTHLY_UPDATE_LOG
FOR EACH ROW 
BEGIN
 SELECT MONTHLY_UPDATE_LOG_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
exception
  when others then
    raise_application_error(-20010,'Ошибка в MONTHLY_UPDATE_LOG_TRG'||sqlerrm);
end;
/

