CREATE OR REPLACE TRIGGER U1.ONLINE_UPDATE_LOG_TRG
BEFORE INSERT ON ONLINE_UPDATE_LOG
FOR EACH ROW 
BEGIN
 SELECT ONLINE_UPDATE_LOG_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
exception
  when others then
    raise_application_error(-20010,'Ошибка в ONLINE_UPDATE_LOG_TRG'||sqlerrm);
end;
/

