CREATE OR REPLACE TRIGGER U1.T_RDWH_INCREM_CHECK_PARAM_TRG BEFORE INSERT ON T_RDWH_INCREM_CHECK_PARAM
FOR EACH ROW
BEGIN

  BEGIN
    IF :NEW.ID IS NULL THEN
      SELECT T_RDWH_INCREM_CHECK_PARAM_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;

    END IF;
    :NEW.IS_USED := 1;
  END;
END;
/

