CREATE OR REPLACE FORCE VIEW U1.TTT AS
select "ID","USERFIRSTNAMERUS","USERLASTNAMERUS","USERMIDDLENAMERUS","USERFIRSTNAMEENG","USERLASTNAMEENG","USERMIDDLENAMEENG","ISBLOCKED","USERBLOCKDATE","USERBLOCKREASON","WRONGAUTHTRIES","ISSYSTEMACCOUNT","REGDATE","DATEOFBIRTH","ISRESIDENT","RNN","INN","IDENTITYDOCTYPE","IDENTITYDOCNUMBER","IDENTITYDOCISSUER","IDENTITYDOCEXPIREDATE","COUNTRY","REGION","CITY","ADDRESS","PHONES","ISREGISTRATIONCONFIRMED","ISREGCODEENTERED","LASTAUTHMETHOD","REGCODEENTRYATTEMPTCOUNT","REGCONFIRMATIONCODEHASH","USERTYPE","ISWALLETUSER","USERACCESSTYPE","ISTOP","USERBLOCKTYPE","SELECTEDREGIONID","PREVIOUSUSERACCESSTYPE","DATEOFACCESSTYPECHANGING" from s37.tb_Framework_Users@rdwh_exd;
grant select on U1.TTT to LOADDB;


