create or replace force view u1.v_behavioral_scoring_2_old as
select t."YY_MM_REPORT",t."YY_MM_END_DATE",t."RFO_CLIENT_ID",t."CON_AMOUNT_FIRST_SUM",t."CON_START_FACT_PMTS_MIN",t."CON_START_FACT_PMTS_MAX",t."CON_START_UNDONE_PMTS_MIN",t."CON_START_UNDONE_PMTS_MAX",t."CON_START_DEL_DAYS_MIN",t."CON_START_DEL_DAYS_MAX",t."CON_START_PMT_MAX_BY_CLI",t."CON_PKB_TOTAL_DEBT",t."CON_PKB_PMT_ACTIVE_ALL_SUM",t."PORT_CONTRACT_AMOUNT_SUM",t."PORT_TOTAL_DEBT_SUM",t."PORT_DELINQ_DAYS_MAX",t."DELING_DAYS_ON_DATE",t."PORT_PMT_BY_CLI_SUM",t."PORT_PLANNED_PMTS_BY_CLI_SUM",t."PORT_FACT_PMTS_BY_CLI_SUM",t."PORT_BRANCH_NAME_FIRST",t."PORT_BRANCH_NAME_LAST",t."PORT_PRODUCT_REFIN_FIRST",t."PORT_PRODUCT_REFIN_LAST",t."IS_HIGH_DELING",t."CON_FIRST_PMT_DELINQ_MIN",t."CON_FIRST_PMT_DELINQ_MAX",t."CON_FIRST_PMT_DELING_SUM",t."CON_FIRST_PMT_DELINQ_AVG",t."CON_FOUR_PMTS_DEL_MAX_MIN",t."CON_FOUR_PMTS_DEL_MAX_MAX",t."CON_FOUR_PMTS_DEL_MAX_SUM",t."CON_FOUR_PMTS_DEL_MAX_AVG",t."CON_FOUR_PMTS_UNDONE_PMTS_MIN",t."CON_FOUR_PMTS_UNDONE_PMTS_MAX",t."CON_FOUR_PMTS_UNDONE_PMTS_SUM",t."CON_FOUR_PMTS_UNDONE_PMTS_AVG",t."UNDONE_PMTS_THREE_MONTHS",t."UNDONE_PMTS_SIX_MONTHS",t."UNDONE_PMTS_TWELVE_MONTHS",t."FORM_SALARY",t."FORM_PRESCORING_RESULT_FIRST",t."FORM_PRESCORING_RESULT_LAST",t."PORT_PKB_TOTAL_DEBT",t."PORT_PKB_PMT_ACTIVE_ALL_SUM",t."PORT_GCVP_SAL",t."GCVP_SAL_TO_START_PMT"
from V_BEHAVIORAL_SCORING t
where t.yy_mm_report = '2013 - 02';
grant select on U1.V_BEHAVIORAL_SCORING_2_OLD to LOADDB;
grant select on U1.V_BEHAVIORAL_SCORING_2_OLD to LOADER;


