create or replace force view u1.v_cube_portfolio as
select /*+parallel(5)*/
p."ID",p."REPORT_YEAR",p."YY_MM_REPORT",p."CONTRACT_NUMBER",p."CLIENT_ID",p."FOLDER_ID_FIRST",p."TOTAL_DEBT",p."DELINQ_DAYS",p."DELINQ_DAYS_OLD",p."REPORT_MONTH",p."NUM_MONTHS",p."IS_CARD",p."STATUS",p."YY_MM_START",p."START_YEAR",p."DELINQ",p."DEL_LONG",p."DEL_LONG_OLD",p."DEL_LONG_OLD_5",p."CONTRACT_AMOUNT_CATEG",p."PLANNED_PMT_MONTH",p."DELINQ_MM",p."DELINQ_TYPE",p."FACT_PMTS",p."PROVISION",p."REPORT_MONTH_ALL_CONTRACTS",p."REPORT_MONTH_ALL_CONTRACTS_N",p."NEW_TOTAL_DEBT",p."MAX_DEBT_USED",p."DELINQ_AMOUNT"
from V_PORTFOLIO p;
grant select on U1.V_CUBE_PORTFOLIO to LOADDB;
grant select on U1.V_CUBE_PORTFOLIO to LOADER;


