create or replace force view u1.v_dwh_dict_operation_type as
select "OPERATION_TYPE_CD","OPERATION_TYPE$CHANGE_DATE","OPERATION_TYPE$ROW_STATUS","OPERATION_TYPE$AUDIT_ID","OPERATION_TYPE$HASH","OPERATION_TYPE_NAME","OPERATION_TYPE_CODE","OPERATION_TYPE$SOURCE","OPERATION_TYPE$PROVIDER","OPERATION_TYPE$SOURCE_PK","OPERATION_TYPE_PARENT_CD","OPERATION_TYPE_DESCRIPTION","OPERATION_TYPE_REVERSE_FLG","OPERATION_TYPE_RVRS_OP_TYP_CD","OPERATION_TYPE_PLAN_OP_TYP_CD" from dwh_main.dict_operation_type@DWH_PROD2;
grant select on U1.V_DWH_DICT_OPERATION_TYPE to LOADDB;
grant select on U1.V_DWH_DICT_OPERATION_TYPE to LOADER;


