create or replace force view u1.v_gcvp_report_folder as
select distinct "GCVP_REP_ID","FOLDER_ID","REP_DATE","CLIENT_RNN","CLIENT_IIN","ERROR_CODE","SALARY","MAX_PMT_DATE","MIN_PMT_DATE","PMTS_COUNT_FROM_REP","PMTS_COUNT_ALL","PMTS_COUNT_10D","PMTS_COUNT_20D","PMTS_COUNT_30D","PMTS_COUNT_40D","PMTS_COUNT_50D","PMTS_COUNT_60D","REP_PMT_MAX_DATE_DIFF","REP_PMT_MIN_DATE_DIFF","ORG_COUNT","PMTS_PER_DAY_MAX","PMTS_PER_DAY_MAX_DATE","PMTS_PER_DAY_MAX_ORG_RNN_BIN","MIN_ORG_PMT_DATE" from V_GCVP_REPORT t
where t.folder_id is not null;
grant select on U1.V_GCVP_REPORT_FOLDER to LOADDB;
grant select on U1.V_GCVP_REPORT_FOLDER to LOADER;


