create or replace force view u1.v_loader_1 as
select /*+ noparallel */ t."RFO_BLACK_LIST_ID",t."IIN",t."RNN",t."SURNAME",t."FIRST_NAME",t."PATRONYMIC",t."BIRTH_DATE",t."REMOVE_DATE",t."REMOVE_REASON",t."REMOVE_USER_NAME",t."REMOVE_USER_NUM_TAB",t."ADD_DATE",t."ADD_REASON",t."ADD_NOTE",t."ADD_USER_NAME_ADD",t."ADD_USER_NUM_TAB",t."PERS_DOC_TYPE",t."PERS_DOC_NUM",t."PERS_DOC_ISSUER",t."PERS_DOC_DATE_BEGIN",t."PERS_DOC_DATE_END",t."PERS_DOC_ISSUE_PLACE",t."ADDRESS",t."PLACE_OF_BIRTH",t."REMOVE_USER_LOGIN",t."ADD_USER_LOGIN",t."DEP_NAME",t."DEP_CODE",t."DATE_EDIT"
   from V_RFO_BLACK_LIST_REMOVED t;
grant select on U1.V_LOADER_1 to LOADDB;
grant select on U1.V_LOADER_1 to LOADER;


