create or replace force view u1.v_nps_kaspi_shop as
select "FOLDER_ID_MIN","IS_CLIENT_BANK","CLIENT_NAME","CLIENT_IIN","PHONE_NUMBER","BIRTH_DATE","FOLDER_DATE_CREATE_MIN","DATE_GOODS_TAKE_MAX","GOODS_TYPE_NAME_LIST","GOODS_NAME_LIST","SHOP_NAME_LIST","PARTNER_LIST","CONTRACT_AMOUNT_LIST","C_PRICE_LIST","PROD_TYPE_LIST","IS_BANK_EMPLOYEE","IS_SIGN"
  from u1.M_NPS_KASPI_SHOP;
grant select on U1.V_NPS_KASPI_SHOP to LOADDB;
grant select on U1.V_NPS_KASPI_SHOP to LOADER;
grant select on U1.V_NPS_KASPI_SHOP to NPS;


