create or replace force view u1.v_out_optimization_after as
select /*+ parallel 5 */ "CLIENT_ID","CONTRACT_NUMBER","NEW_TARIFF","OLD_TARIFF","OP_RANGE_DAYS","OP_RANGE_MONTHS","SOGLASIE","SPECIAL_OFFER","OP_CHANNEL","OP_DATE_START","OP_DATE_FINISH","DEL_DAYS_CLI","DEL_DAYS_CON","TOTAL_DEBT","YY_MM_REPORT" from u1.M_OUT_OPTIMIZATION_AFTER;
grant select on U1.V_OUT_OPTIMIZATION_AFTER to IT6_USER;
grant select on U1.V_OUT_OPTIMIZATION_AFTER to LOADDB;
grant select on U1.V_OUT_OPTIMIZATION_AFTER to LOADER;


