create or replace force view u1.v_out_folder_ekt as
select /*+ noparallel */ RFO_CLIENT_ID,RFO_CONTRACT_ID,FOLDER_ID,CLAIM_ID,CR_PROGRAM_NAME,PROCESS_NAME,CONTRACT_NUMBER,POS_CODE,POS_NAME,START_MONTH,BEGIN_DATE,CONTRACT_TERM_DAYS,ACTUAL_END_DATE,CONTRACT_TERM_MONTHS,PRODUCER,PRODUCT_NAME,PRODUCT_MODEL,QUANTITY,GOODS_COST,BILL_SUM,GOODS_PRICE,KIND_NAME,TOV_CATEG_CODE,TOV_CATEG_NAME,TOV_NAME_CODE,TOV_NAME_NAME,TN_TOV_TYPE_CODE,TN_TOV_TYPE_NAME,TN_TOV_CATEG_CODE,TN_TOV_CATEG_NAME,TN_TOV_TYPE_CODE_ROOT,TN_TOV_TYPE_NAME_ROOT,CONTRACT_AMOUNT,PRODUCT_TYPE_NAME,CLIENT_RNN,CLIENT_IIN,CLIENT_NAME,RFO_SHOP_ID,SHOP_CODE,SHOP_NAME,CITY_NAME,FIL_NAME,UNP_NAME,GOODS_ID,SERVISE_ID,INITIAL_PAYMENT,DATE_CREATE,IS_CREDIT_ISSUED  from u1.v_folder_ekt;
grant select on U1.V_OUT_FOLDER_EKT to LOADDB;
grant select on U1.V_OUT_FOLDER_EKT to UPD_USER;


