create or replace force view u1.v_out_rfo_black_list as
selecT "RFO_BLACK_LIST_ID","IIN","RNN","SURNAME","FIRST_NAME","PATRONYMIC","BIRTH_DATE_TEXT","ADD_REASON","NOTE","DATE_ADD_TEXT","USER_NAME","USER_NUM_TAB","PERS_DOC_TYPE","PERS_DOC_NUM","PERS_DOC_ISSUER","PERS_DOC_DATE_BEGIN_TEXT","PERS_DOC_DATE_END_TEXT","PERS_DOC_ISSUE_PLACE","ADDRESS","PLACE_OF_BIRTH","USER_LOGIN","DEP_NAME","DEP_CODE","DATE_EDIT_TEXT","YY_MM_REPORT_MAX_MAX","YY_MM_REPORT_MAX_MIN","DELINQ_DAYS_MAX_MAX","DELINQ_DAYS_MAX_MIN","TOTAL_PMTS_MAX","TOTAL_PMTS_MIN","IS_ERROR","X_IIN","BISQUIT_DEL_IIN","DEL_LONG_MAX_MAX","DEL_LONG_MAX_MIN","NOTE_TYPE","MONTHS_AFTER_YY_MM_REPORT_MAX","NOTE_TYPE_PRIORITY","NOTE_TYPE_PRIORITY_IMP","NOTE_TYPE_IMP","IS_FOR_REMOVAL" from v_rfo_black_list t
 where t.note in ('А0000013','A0000013','A7','А7');
grant select on U1.V_OUT_RFO_BLACK_LIST to IT6_USER;
grant select on U1.V_OUT_RFO_BLACK_LIST to LOADDB;
grant select on U1.V_OUT_RFO_BLACK_LIST to LOADER;


