create or replace force view u1.v_rbo_z#kas_pc_card as
select "ID","CLASS_ID","STATE_ID","C_CARD_NUM","C_DATE_CREATE","C_DATE_END","C_VID_CARD_REF","C_CURRENCY_REF","C_PACK_REF","C_IS_PERSONAL","C_ACC_NUM","C_REFRESH_TM","C_EMBOSSING_NAME","C_ERR_TXT","C_RISK_ARR","C_RISK_REF","C_DATE_INACTIVE","C_DEPART_REF","C_PACK_NONAME_REF","C_PACK_SORT_REF","C_TEXT","C_PACK_DLVR_REF","C_DATE_END_OLD","C_REEMBOSS_REF","C_DATE_TAKE","C_CARD_NUM_OLD","C_DATE_ACTIVATE","C_ACC_REF","C_ACC_NUM_TM","C_RUN_REEMBOSS","C_CARD_NUM_CRYPT","C_CLIENT_REF","C_IS_LOSE","C_CARD_NUM_ROLLBCK","SN","SU" from GG_RBO.Z#KAS_PC_CARD;
grant select on U1.V_RBO_Z#KAS_PC_CARD to LOADDB;


