create or replace force view u1.v_rsdiana_online_param1 as
select "RFO_CLIENT_ID","DATE_CREATE","CLAIM_ID","SHOP_CODE","SHOP_NAME","STATUS_CODE","STATUS_NAME","PROCESS_ID","INCOME_FORM","INCOME_FORM_ALL","AGE","REG_KASPIKZ_LENGTH","AVG_SUM_PAY_KSPKZ_30_D","COUNT_MONTH_KASPIKZ_6_M","COUNT_PAY_KSPKZ_30_D","COUNT_SERV_KSPKZ_6_M","KOMMUNALKA_KASPIKZ_6_M","COUNT_MOB_KSPKZ","SUM_PAY_KSPKZ_30_D","SHARE_MONTH_KASPIKZ_6_M","SESSION_KSP_LAST_6_MNTH","COUNT_DAY_APP_ONL","MAX_SUM_ONLINE_EKT_3_M","COUNT_APPL_KN_30_D","COUNT_FAIL_KN_30_D","MAX_SUM_APPL_KN_30_D","COUNT_FAIL_30_D","COUNT_APPLICATIONS_30_D","COUNT_APPLICATIONS_30_D_X","MAX_COUNT_FAIL_ONL_DAY","LAST_YEAR_MAX_DELAY","PKB_DEBT_KZT","INCOME_GCVP","DAYS_LAST_GCVP","DIFF_ZP_FORM_GCVP","DIFF_ZP_FORM_ALL_GCVP","AVG_SUM_PAY_CRED_3_M","COUNT_VISIT_GUEST","COUNT_SALARY_6_M","KASPI_GOLD_ACTIVE","MAX_TOV_CATEG_CODE","MAX_COUNT_CATEGORY_DAY","COUNT_CATEGORY_3_M","COUNT_CATEGORY_3_M_X","MAX_PROD_MODELS_DAY","MAX_COUNT_MODELS_DAY","EX_TERMINAL_SHARE_COUNT","FAIL_SHARE_30_D_COUNT","TERMINAL_SHARE_COUNT","SHARE_30_D_COUNT","EX_TERMINAL_SHARE","FAIL_SHARE_30_D","AVG_ZP_H","II"
from u1.M_RFO_FRAUD_SEARCH
where process_id is not null and date_create >= to_date('01-01-2016', 'dd-mm-yyyy');
grant select on U1.V_RSDIANA_ONLINE_PARAM1 to LOADDB;
grant select on U1.V_RSDIANA_ONLINE_PARAM1 to UPD_USER;


