create or replace force view u1.v_sas_out_gcvp_report as
select --+ parallel(5)
"GCVP_REP_ID","FOLDER_ID","REP_DATE","CLIENT_RNN","CLIENT_IIN","ERROR_CODE","SALARY","MAX_PMT_DATE","MIN_PMT_DATE","PMTS_COUNT_FROM_REP","PMTS_COUNT_ALL","PMTS_COUNT_10D","PMTS_COUNT_20D","PMTS_COUNT_30D","PMTS_COUNT_40D","PMTS_COUNT_50D","PMTS_COUNT_60D","REP_PMT_MAX_DATE_DIFF","REP_PMT_MIN_DATE_DIFF","ORG_COUNT","PMTS_PER_DAY_MAX","PMTS_PER_DAY_MAX_DATE","PMTS_PER_DAY_MAX_ORG_RNN_BIN","MIN_ORG_PMT_DATE","ORIG_REPORT_ID","IS_FROM_CACHE","ORG_BIN_LAST","ORG_RNN_LAST" from V_GCVP_REPORT t
;
grant select on U1.V_SAS_OUT_GCVP_REPORT to IT6_USER;
grant select on U1.V_SAS_OUT_GCVP_REPORT to LOADDB;
grant select on U1.V_SAS_OUT_GCVP_REPORT to LOADER;


