create or replace force view u1.v_tmp_d_products1 as
select "CR_PROGRAM_NAME","CONTRACT_NUMBER","POS_CODE","POS_NAME","START_MONTH","BEGIN_DATE","CONTRACT_TERM_DAYS","ACTUAL_END_DATE","CONTRACT_TERM_MONTHS","PRODUCER","PRODUCT_NAME","PRODUCT_MODEL","QUANTITY","GOODS_COST","BILL_SUM","GOODS_PRICE","CONTRACT_AMOUNT","PRODUCT_TYPE_NAME","CLIENT_RNN","CLIENT_IIN","CLIENT_NAME","RFO_SHOP_ID","SHOP_CODE","SHOP_NAME","CITY_NAME","FIL_NAME","UNP_NAME","GOODS_ID","SERVISE_ID","INITIAL_PAYMENT" from v_contract_ekt_dwh
where begin_date>='01-01-2014';
grant select on U1.V_TMP_D_PRODUCTS1 to LOADDB;
grant select on U1.V_TMP_D_PRODUCTS1 to LOADER;


