create or replace force view u1.vx_1 as
select /*+noparallel*/ "RFO_BLACK_LIST_ID","IIN","RNN","SURNAME","FIRST_NAME","PATRONYMIC","BIRTH_DATE","REMOVE_DATE","REMOVE_REASON","REMOVE_USER_NAME","REMOVE_USER_NUM_TAB","ADD_DATE","ADD_REASON","ADD_NOTE","ADD_USER_NAME_ADD","ADD_USER_NUM_TAB","PERS_DOC_TYPE","PERS_DOC_NUM","PERS_DOC_ISSUER","PERS_DOC_DATE_BEGIN","PERS_DOC_DATE_END","PERS_DOC_ISSUE_PLACE","ADDRESS","PLACE_OF_BIRTH","REMOVE_USER_LOGIN","ADD_USER_LOGIN","DEP_NAME","DEP_CODE","DATE_EDIT" from V_RFO_BLACK_LIST_REMOVED;
grant select on U1.VX_1 to LOADDB;
grant select on U1.VX_1 to LOADER;


